FROM sourcegraph/src-cli:3.31.0@sha256:3b4c76b5a50eb297e96eb7cb8438a109b1b8e2e3aa0f4f90874f05851cf02b64 AS src-cli

FROM node:14.17.4-alpine3.14@sha256:60a5e65ced8bad91a4c57c05a474baa01182b2b773eb50380e4a90ad4b3e6358

ENV NODE_OPTIONS=--max-old-space-size=4096

RUN apk add --no-cache git bash curl ca-certificates python3 make libstdc++ libgcc gcc g++ pkgconfig python2 automake autoconf

COPY --from=src-cli /usr/bin/src /usr/bin

RUN npm install --global n@latest @sourcegraph/lsif-tsc@latest

CMD ["/bin/sh"]
